"""Re-running a recorded trajectory without calling a model.

Two uses, both of which come up constantly once evaluations are real:

* **Re-scoring history.** Change an evaluator, then replay last month's runs
  through it. Without this you either pay for every historical run again or you
  compare new scores against old ones computed by different code.
* **Turning a production trace into a regression case.** A trace captured from
  a real interaction becomes a fixture that reproduces exactly, for free, on
  every future build.

Replay re-executes the recorded *tool calls* against a fresh workspace rather
than replaying recorded results. That distinction matters: the point is to
arrive at the same final workspace state so outcome evaluators can run against
it for real, not to parrot a transcript. Recorded model calls are re-emitted
with zero cost and ``cached=True``, because those tokens were spent once already.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

from pydantic import JsonValue

from evalforge.agent.base import Agent, AgentContext
from evalforge.agent.tools import ToolBox
from evalforge.hashing import content_hash
from evalforge.schema.trajectory import AgentError, ModelCall, ToolCall, Trajectory


class ReplayError(Exception):
    """A trajectory could not be replayed."""


def load_trajectory(
    path: Path, *, run_id: str = "", case_id: str = "", attempt: int = 0
) -> Trajectory:
    """Read a trajectory from the JSONL file the runner writes."""
    if not path.is_file():
        raise ReplayError(f"no trajectory file at {path}")
    try:
        return Trajectory.from_jsonl(
            run_id=run_id or path.parent.name,
            case_id=case_id or path.stem.rsplit("--", 1)[0],
            attempt=attempt,
            jsonl=path.read_text(encoding="utf-8"),
        )
    except (OSError, ValueError) as exc:
        raise ReplayError(f"could not read trajectory at {path}: {exc}") from exc


@dataclass(slots=True)
class ReplayAgent(Agent):
    """Replays the tool calls of a recorded trajectory."""

    trajectory: Trajectory
    label: str = "replay"
    _skipped: list[str] = field(default_factory=list, init=False)

    @property
    def name(self) -> str:
        return f"replay:{self.label}"

    def config(self) -> dict[str, JsonValue]:
        return {
            "source_run_id": self.trajectory.run_id,
            "source_case_id": self.trajectory.case_id,
            "source_attempt": self.trajectory.attempt,
            # Pins the exact trace: replaying a different one is a different agent.
            "source_hash": content_hash(
                [json.loads(event.model_dump_json()) for event in self.trajectory.events]
            ),
        }

    @property
    def skipped_calls(self) -> tuple[str, ...]:
        """Tool calls that could not be replayed, in order."""
        return tuple(self._skipped)

    async def run(self, context: AgentContext) -> None:
        recorder = context.recorder
        tools = ToolBox(case=context.case, workspace=context.workspace, recorder=recorder)

        recorder.task_started(prompt_hash=context.case.content_hash)

        for event in self.trajectory.events:
            if isinstance(event, ModelCall):
                recorder.model_call(
                    model=event.model,
                    input_tokens=event.input_tokens,
                    output_tokens=event.output_tokens,
                    # The spend already happened; charging it twice would make a
                    # replayed run look as expensive as the original.
                    cost_usd=0.0,
                    latency_ms=event.latency_ms,
                    cached=True,
                    stop_reason=event.stop_reason,
                )
            elif isinstance(event, ToolCall):
                await self._replay_call(tools, event)
            elif isinstance(event, AgentError):
                recorder.agent_error(error_type=event.error_type, message=event.message)
            # Results, edits and command runs are regenerated by re-executing
            # the calls above, so replaying them too would double every event.

    async def _replay_call(self, tools: ToolBox, event: ToolCall) -> None:
        match event.tool:
            case "list_files":
                tools.list_files()
            case "read_file":
                path = _string_argument(event, "path")
                if path is None:
                    self._skipped.append(event.tool)
                    return
                tools.read_file(path)
            case "write_file":
                path = _string_argument(event, "path")
                contents = _string_argument(event, "contents")
                if path is None or contents is None:
                    # A trace recorded before contents were captured cannot be
                    # replayed faithfully; skipping loudly beats a silent
                    # divergence in the final workspace state.
                    self._skipped.append(event.tool)
                    return
                tools.write_file(path, contents)
            case "run_tests":
                await tools.run_tests()
            case "submit":
                tools.submit(_string_argument(event, "summary") or "")
            case _:
                self._skipped.append(event.tool)


def _string_argument(event: ToolCall, name: str) -> str | None:
    value = event.args.get(name)
    return value if isinstance(value, str) else None
